# ==========================================================================
# CRE PROJECT SETTINGS FILE — UrbanLeaf AI
# ==========================================================================

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://sepolia-rollup.arbitrum.io/rpc

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://sepolia-rollup.arbitrum.io/rpc
